#
# 이 파일은 도커를 관리하는 파일입니다. 
#
version: '2'
services:
    supergate-dev-base:
        build:
            context     : ./
            dockerfile  : Dockerfile
        image           : thhan/supergate-dev-base:${DOCKER_IMG_TAG}
        platform        : linux/amd64
